Repository nhnacademy-be10-WannaB/wannab-front, pull requests merged in 2025-06, with the labels that each got.

#15 #9/front-deploy : Gihub Actions + 롤링 무중단 배포 구현
  .github/workflows/front-deploy.yml
  .github/workflows/test-on-pr.yml
  Dockerfile
  pom.xml
  src/main/java/shop/wannab/frontservice/FrontserviceApplication.java
  src/main/resources/application-local.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: CI / CD

#38 Feature/issue 37/order detail read (비회원)
  src/main/java/shop/wannab/frontservice/deliveryPolicy/OrderApiClient.java
  src/main/java/shop/wannab/frontservice/order/client/OrderApiClient.java
  src/main/java/shop/wannab/frontservice/order/list/deliveryPolicy/DeliveryPolicyController.java
  src/main/java/shop/wannab/frontservice/order/list/deliveryPolicy/dto/DeliveryPolicyRequest.java
  src/main/java/shop/wannab/frontservice/order/list/deliveryPolicy/dto/DeliveryPolicyResponse.java
  src/main/java/shop/wannab/frontservice/order/list/orderDetail/OrderDetailController.java
  src/main/java/shop/wannab/frontservice/order/list/orderDetail/dto/OrderBookDetailResponse.java
  src/main/java/shop/wannab/frontservice/order/list/orderDetail/dto/OrderDetailResponse.java
  src/main/java/shop/wannab/frontservice/order/list/ordersManagement/OrderManagementController.java
  src/main/java/shop/wannab/frontservice/order/list/ordersManagement/dto/OrderListResponse.java
  src/main/java/shop/wannab/frontservice/order/list/ordersManagement/dto/OrderStatus.java
  src/main/java/shop/wannab/frontservice/order/list/ordersManagement/dto/PageResponse.java
  src/main/java/shop/wannab/frontservice/order/list/wrappingPolicy/WrappingPaperController.java
  src/main/java/shop/wannab/frontservice/order/list/wrappingPolicy/dto/WrappingPaperRequest.java
  src/main/java/shop/wannab/frontservice/order/list/wrappingPolicy/dto/WrappingPaperResponse.java
  src/main/resources/templates/user/main-non-member-order-detail.html
  src/main/resources/templates/user/main-non-member-order.html
Labels: Feature, Front

#43 <41/이슈이름 : 회원 소지 쿠폰 조회>
  pom.xml
  src/main/java/shop/wannab/frontservice/FrontserviceApplication.java
  src/main/java/shop/wannab/frontservice/controller/MypageController.java
  src/main/java/shop/wannab/frontservice/couponpolicy/CategoryHierarchyDto.java
  src/main/java/shop/wannab/frontservice/couponpolicy/CouponApiClient.java
  src/main/java/shop/wannab/frontservice/couponpolicy/CouponController.java
  src/main/java/shop/wannab/frontservice/couponpolicy/CouponResponseToUserDto.java
  src/main/java/shop/wannab/frontservice/couponpolicy/PageResponseDto.java
  src/main/resources/static/css/user/mypage-coupon.css
  src/main/resources/static/js/admin-coupon.js
  src/main/resources/templates/admin/coupon.html
  src/main/resources/templates/components/mypage-sidebar.html
  src/main/resources/templates/user/mypage-coupon.html
Labels: Feature, Front

#46 #42/dev-prod-setup : 개발 환경 분리 및 리팩토링
  .github/workflows/test-on-pr.yml
  .gitignore
  pom.xml
  src/main/java/shop/wannab/frontservice/address/controller/AddressController.java
  src/main/java/shop/wannab/frontservice/address/service/Impl/AddressServiceImpl.java
  src/main/java/shop/wannab/frontservice/auth/service/AuthClient.java
  src/main/java/shop/wannab/frontservice/auth/service/AuthService.java
  src/main/java/shop/wannab/frontservice/controller/AdminController.java
  src/main/java/shop/wannab/frontservice/controller/MypageController.java
  src/main/java/shop/wannab/frontservice/couponpolicy/CouponApiClient.java
  src/main/java/shop/wannab/frontservice/couponpolicy/CouponController.java
  src/main/java/shop/wannab/frontservice/couponpolicy/CouponPolicyCreateDto.java
  src/main/java/shop/wannab/frontservice/global/config/WebConfig.java
  src/main/java/shop/wannab/frontservice/order/client/OrderApiClient.java
  src/main/java/shop/wannab/frontservice/order/controller/CartController.java
  src/main/java/shop/wannab/frontservice/order/controller/OrderController.java
  src/main/java/shop/wannab/frontservice/order/dto/WrappingPaperResponse.java
  src/main/java/shop/wannab/frontservice/order/list/deliveryPolicy/DeliveryPolicyController.java
  src/main/java/shop/wannab/frontservice/order/list/deliveryPolicy/dto/DeliveryPolicyRequest.java
  src/main/java/shop/wannab/frontservice/order/list/deliveryPolicy/dto/DeliveryPolicyResponse.java
  src/main/java/shop/wannab/frontservice/order/list/orderDetail/dto/OrderBookDetailResponse.java
  src/main/java/shop/wannab/frontservice/order/list/orderDetail/dto/OrderDetailResponse.java
  src/main/java/shop/wannab/frontservice/order/list/ordersManagement/dto/OrderListResponse.java
  src/main/java/shop/wannab/frontservice/order/list/ordersManagement/dto/OrderStatus.java
  src/main/java/shop/wannab/frontservice/order/list/ordersManagement/dto/PageResponse.java
  src/main/java/shop/wannab/frontservice/order/list/wrappingPolicy/WrappingPaperController.java
  src/main/java/shop/wannab/frontservice/order/list/wrappingPolicy/dto/WrappingPaperRequest.java
  src/main/java/shop/wannab/frontservice/order/list/wrappingPolicy/dto/WrappingPaperResponse.java
  src/main/java/shop/wannab/frontservice/user/client/UserClient.java
  src/main/java/shop/wannab/frontservice/user/controller/UserController.java
  src/main/java/shop/wannab/frontservice/user/dto/UserResponse.java
  src/main/java/shop/wannab/frontservice/user/service/Impl/PointServiceImpl.java
  src/main/java/shop/wannab/frontservice/user/service/Impl/UserServiceImpl.java
  src/main/java/shop/wannab/frontservice/user/service/UserService.java
  src/main/resources/application-ci.yml
  src/main/resources/application.yml
  src/main/resources/properties/env.properties
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/components/header.html
Labels: CI / CD, Refactor

#50 - 제목 : <44/이슈이름 : 결제 기능>
  src/main/java/shop/wannab/frontservice/order/controller/OrderController.java
  src/main/resources/application-ci.yml
  src/main/resources/static/js/main-order.js
  src/main/resources/templates/user/main-order.html
Labels: Feature, Refactor
