Repository nhnacademy-be10-WannaB/wannab-front, pull requests merged in 2025-07, with the labels that each got.

#58 - 제목 : <40/이슈이름 : 쿠폰 발급 기능>
  src/main/java/shop/wannab/frontservice/couponpolicy/BookController.java
  src/main/java/shop/wannab/frontservice/couponpolicy/CouponApiClient.java
  src/main/java/shop/wannab/frontservice/couponpolicy/IssuableCouponDto.java
  src/main/java/shop/wannab/frontservice/couponpolicy/PageResponseDto.java
  src/main/resources/static/css/user/main-book-detail.css
  src/main/resources/templates/components/header.html
  src/main/resources/templates/user/main-book-detail.html
Labels: Feature, Front

#61 #36/알라딘 API를 활용한 도서 조회 기능 구현
  pom.xml
  src/main/java/shop/wannab/frontservice/book/client/AdminBookClient.java
  src/main/java/shop/wannab/frontservice/book/client/request/SearchRequest.java
  src/main/java/shop/wannab/frontservice/book/client/response/SearchBookItem.java
  src/main/java/shop/wannab/frontservice/book/client/response/SearchResponse.java
  src/main/java/shop/wannab/frontservice/book/controller/AdminBookController.java
  src/main/java/shop/wannab/frontservice/book/controller/request/SearchBookRequest.java
  src/main/java/shop/wannab/frontservice/book/controller/response/BookItem.java
  src/main/java/shop/wannab/frontservice/book/controller/response/SearchBookResponse.java
  src/main/java/shop/wannab/frontservice/book/service/AdminBookService.java
  src/main/java/shop/wannab/frontservice/deliveryPolicy/OrderApiClient.java
  src/main/java/shop/wannab/frontservice/global/Interceptor/FeignJwtInterceptor.java
  src/main/java/shop/wannab/frontservice/global/config/FeignConfig.java
  src/main/java/shop/wannab/frontservice/global/config/ObjectMapperConfig.java
  src/main/resources/templates/admin/aladin-book-form.html
  src/main/resources/templates/admin/book.html
  src/main/resources/templates/admin/coupon.html
  src/main/resources/templates/admin/delivery-policy.html
  src/main/resources/templates/admin/order.html
  src/main/resources/templates/admin/point.html
  src/main/resources/templates/admin/wrapping-papers.html
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/components/footer.html
  src/main/resources/templates/error/400.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/500.html
  src/main/resources/templates/layout/admin-layout.html
  src/main/resources/templates/layout/user-mypage-layout.html
Labels: Feature, Front

#74 #62/알라딘 API를 활용한 도서 등록 기능 구현
  pom.xml
  src/main/java/shop/wannab/frontservice/book/client/AdminBookClient.java
  src/main/java/shop/wannab/frontservice/book/controller/AdminBookController.java
  src/main/java/shop/wannab/frontservice/book/controller/request/AladinBookRequest.java
  src/main/java/shop/wannab/frontservice/book/controller/response/BookItem.java
  src/main/java/shop/wannab/frontservice/book/exception/BookServiceException.java
  src/main/java/shop/wannab/frontservice/book/service/AdminBookService.java
  src/main/java/shop/wannab/frontservice/global/advice/GlobalExceptionHandler.java
  src/main/java/shop/wannab/frontservice/global/config/FeignConfig.java
  src/main/resources/templates/admin/aladin-book-form.html
Labels: Feature, Front

#99 feat: 소셜 로그인/회원가입 기능 구현
  pom.xml
  src/main/java/shop/wannab/frontservice/auth/PaycoClient.java
  src/main/java/shop/wannab/frontservice/auth/ResponseCode.java
  src/main/java/shop/wannab/frontservice/auth/domain/PaycoLoginRequest.java
  src/main/java/shop/wannab/frontservice/auth/domain/PaycoLoginResponse.java
  src/main/java/shop/wannab/frontservice/auth/domain/PaycoUserResponse.java
  src/main/java/shop/wannab/frontservice/auth/domain/PrincipalDetails.java
  src/main/java/shop/wannab/frontservice/auth/domain/Response.java
  src/main/java/shop/wannab/frontservice/auth/domain/TokenRequest.java
  src/main/java/shop/wannab/frontservice/auth/domain/TokenResponse.java
  src/main/java/shop/wannab/frontservice/auth/handler/OAuth2SuccessHandler.java
  src/main/java/shop/wannab/frontservice/auth/service/AuthClient.java
  src/main/java/shop/wannab/frontservice/auth/service/AuthService.java
  src/main/java/shop/wannab/frontservice/auth/service/CustomOAuth2UserService.java
  src/main/java/shop/wannab/frontservice/auth/service/Impl/AuthServiceImpl.java
  src/main/java/shop/wannab/frontservice/global/config/SecurityConfig.java
  src/main/java/shop/wannab/frontservice/user/service/UserService.java
  src/main/resources/application-ci.yml
  src/main/resources/templates/auth/login.html
Labels: Feature

#102 #63/도서 카테고리 등록, 조회, 삭제 기능 구현
  src/main/java/shop/wannab/frontservice/book/client/AdminBookClient.java
  src/main/java/shop/wannab/frontservice/category/client/CategoryClient.java
  src/main/java/shop/wannab/frontservice/category/controller/AdminCategoryController.java
  src/main/java/shop/wannab/frontservice/category/controller/request/CategoryCreateCommand.java
  src/main/java/shop/wannab/frontservice/category/controller/request/CategoryCreateRequest.java
  src/main/java/shop/wannab/frontservice/category/controller/response/CategoryResponse.java
  src/main/java/shop/wannab/frontservice/category/controller/response/PageResponse.java
  src/main/java/shop/wannab/frontservice/category/service/AdminCategoryService.java
  src/main/java/shop/wannab/frontservice/global/config/SecurityConfig.java
  src/main/resources/templates/admin/book-category-manage.html
  src/main/resources/templates/components/admin-sidebar.html
Labels: Feature

#110 휴면상태해제 : <46/user-unlock>
  src/main/java/shop/wannab/frontservice/auth/controller/AuthController.java
  src/main/java/shop/wannab/frontservice/auth/controller/request/UnlockRequest.java
  src/main/java/shop/wannab/frontservice/auth/exception/DeletedUserException.java
  src/main/java/shop/wannab/frontservice/auth/exception/InactiveUserException.java
  src/main/java/shop/wannab/frontservice/auth/filter/CustomLoginFilter.java
  src/main/java/shop/wannab/frontservice/auth/handler/CustomAuthenticationFailureHandler.java
  src/main/java/shop/wannab/frontservice/auth/service/AuthClient.java
  src/main/java/shop/wannab/frontservice/auth/service/AuthService.java
  src/main/java/shop/wannab/frontservice/auth/service/CustomUserDetailsService.java
  src/main/java/shop/wannab/frontservice/auth/service/Impl/AuthServiceImpl.java
  src/main/java/shop/wannab/frontservice/global/advice/GlobalControllerAdvice.java
  src/main/java/shop/wannab/frontservice/global/advice/GlobalExceptionHandler.java
  src/main/resources/templates/auth/unlock.html
Labels: Feature

#116 #96/도서 태그 등록, 조회, 삭제 기능 구현
  src/main/java/shop/wannab/frontservice/book/controller/AdminBookController.java
  src/main/java/shop/wannab/frontservice/category/controller/AdminCategoryController.java
  src/main/java/shop/wannab/frontservice/tag/client/TagClient.java
  src/main/java/shop/wannab/frontservice/tag/controller/AdminTagController.java
  src/main/java/shop/wannab/frontservice/tag/controller/request/TagCreateRequest.java
  src/main/java/shop/wannab/frontservice/tag/controller/response/TagResponse.java
  src/main/java/shop/wannab/frontservice/tag/service/AdminTagService.java
  src/main/resources/application-ci.yml
  src/main/resources/templates/admin/book-category-management.html
  src/main/resources/templates/admin/book-tag-management.html
  src/main/resources/templates/components/admin-sidebar.html
Labels: Feature

#132 issue-130/fix : 포장지관리 중복 dto제거
  src/main/java/shop/wannab/frontservice/order/dto/OrderBookInfo.java
  src/main/java/shop/wannab/frontservice/order/dto/OrderPageRequestDto.java
  src/main/java/shop/wannab/frontservice/order/dto/WrappingPaperResponse.java
  src/main/resources/templates/user/main-cart.html
  src/main/resources/templates/user/main-order.html
Labels: Fix

#164 #133/도서 통합 검색 기능 구현 완료
  src/main/java/shop/wannab/frontservice/search/client/BookSearchClient.java
  src/main/java/shop/wannab/frontservice/search/controller/BookSearchController.java
  src/main/java/shop/wannab/frontservice/search/domain/BookSearchField.java
  src/main/java/shop/wannab/frontservice/search/dto/response/BookSearchResult.java
  src/main/java/shop/wannab/frontservice/search/dto/response/BookSearchSource.java
  src/main/java/shop/wannab/frontservice/search/dto/response/SearchResultWithSectionResponse.java
  src/main/java/shop/wannab/frontservice/search/service/BookSearchService.java
  src/main/resources/static/css/user/book-search-total.css
  src/main/resources/templates/book/search/total.html
  src/main/resources/templates/components/search.html
Labels: Feature

#163 issue-162/fix : 포장지 엔티티 변경
  src/main/java/shop/wannab/frontservice/order/client/OrderApiClient.java
  src/main/java/shop/wannab/frontservice/order/controller/OrderController.java
  src/main/java/shop/wannab/frontservice/order/dto/BookOrderSubmitDto.java
  src/main/java/shop/wannab/frontservice/order/dto/OrderPageRequestDto.java
  src/main/java/shop/wannab/frontservice/order/list/orderDetail/dto/OrderDetailResponse.java
  src/main/java/shop/wannab/frontservice/order/list/wrappingPolicy/WrappingPaperController.java
  src/main/java/shop/wannab/frontservice/order/list/wrappingPolicy/dto/WrappingPaperRequest.java
  src/main/java/shop/wannab/frontservice/order/list/wrappingPolicy/dto/WrappingPaperResponse.java
  src/main/resources/static/js/admin-wrapping.js
  src/main/resources/static/js/main-order.js
  src/main/resources/templates/admin/wrapping-papers.html
  src/main/resources/templates/components/admin-sidebar.html
  src/main/resources/templates/user/main-order.html
  src/main/resources/templates/user/order-detail.html
Labels: Fix

#184 통합 검색 페이지 디자인 완료
  src/main/java/shop/wannab/frontservice/auth/controller/AuthController.java
  src/main/java/shop/wannab/frontservice/book/controller/MainBookController.java
  src/main/java/shop/wannab/frontservice/search/dto/response/BookSearchSource.java
  src/main/resources/static/css/user/book-search-total.css
  src/main/resources/templates/book/search/total.html
Labels: Feature

#206 feat: 로그인 여부 확인 메서드 생성
  src/main/java/shop/wannab/frontservice/auth/exception/RoleNotFountException.java
  src/main/java/shop/wannab/frontservice/auth/service/AuthService.java
  src/main/java/shop/wannab/frontservice/auth/service/Impl/AuthServiceImpl.java
  src/main/java/shop/wannab/frontservice/global/filter/JwtAuthorizationFilter.java
Labels: Feature

#238 hotfix : 주문 휴대폰번호 유효성오류 수정
  src/main/resources/templates/user/main-order.html
Labels: Fix

#250 결제 prefix 변경
  src/main/resources/static/js/main-order.js
Labels: Fix

#253 logback 설정 및 의존성 추가
  pom.xml
  src/main/resources/logback-spring.xml
Labels: Feature
